services:
  mqtt:
    image: eclipse-mosquitto:latest
    hostname: eclispe-mosquitto-host
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  xcel_itron2mqtt:
    container_name: xcel_itron2mqtt
    hostname: xcel_itron2mqtt-host
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    volumes:
      - ./certs:/opt/xcel_itron2mqtt/certs:ro
    environment:
      # MQTT Configuration:
      MQTT_SERVER: "${MQTT_SERVER}"
      MQTT_PORT: "${MQTT_PORT}"
      MQTT_TOPIC_PREFIX: homeassistant/
      MQTT_USER: 
      MQTT_PASSWORD: 
      
      # Meter Configuration
      METER_IP: "${METER_IP}"
      METER_PORT: "${METER_PORT}"
      
      # Certificate Configuration
      CERT_PATH: "${CERT_PATH}"
      CERT_KEY_PATH: "${CERT_KEY_PATH}"
    
      
      # Logging
      LOGLEVEL: "${LOGLEVEL}"
    restart: unless-stopped
    network_mode: host

volumes:
  mosquitto_data:
  mosquitto_log:
